### ISSUE TITLE
Error Loading AFINN, Bing, and Loughran Lexicons

### ISSUE THREAD

**Issue by course-files** [20230821-20231128-BI2-BBIT4-2/BBT4206-R-Lab2c-of15-SentimentAnalysis-champions#2]
I still do not encounter any error on my side when executing your code. This is after installing and loading the "tidytext" package:

``` r
## tidytext - For text mining ----
if (!is.element("tidytext", installed.packages()[, 1])) {
  install.packages("tidytext", dependencies = TRUE)
}
require("tidytext")
```
And after loading the lexicons:
``` r
### NRC ----
nrc <- get_sentiments("nrc")
View(nrc)

### AFINN ----
afinn <- get_sentiments(lexicon = "afinn")
View(afinn)

### Bing ----
View(bing)

### Loughran ----
loughran <- get_sentiments("loughran")
View(loughran)
```

For those getting an error, could you post the error message text here as a response to this issue and then I will look into it.

**Comment by Paula-Wang** [comment]
Error: 'C:/Users/PAULIN~1/AppData/Local/textdata/textdata/Cache/nrc/NRC-Emotion-Lexicon/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt' does not exist.

This is the error for NRC.

**Comment by course-files** [comment]
Does this help:

Execute the following first:
``` r
# Update all the packages
update.packages(ask = "graphics", checkBuilt = TRUE, repos = "https://cloud.r-project.org")

# Some claim that there is a version of tidytext which did not have NRC.
# So you can try download the current original one from GitHub as follows:
library(remotes)
install_github("EmilHvitfeldt/textdata")
install_github("juliasilge/tidytext")

require("textdata")
require("tidytext")
```

Then execute the following second:
``` r
### NRC ----
nrc <- get_sentiments("nrc")
View(nrc)

### AFINN ----
afinn <- get_sentiments(lexicon = "afinn")
View(afinn)

### Bing ----
bing <- get_sentiments("bing")
View(bing)

### Loughran ----
loughran <- get_sentiments("loughran")
View(loughran)
```
I am using the following versions:
``` r
> packageVersion("tidytext")    
[1] '0.4.1'
> packageVersion("textdata")
[1] '0.4.4.9000'
```

**Comment by Paula-Wang** [comment]
Afinn, Bing, Loughran is working but NRC is still not working.

**Comment by course-files** [comment]
Okay. Then we can get NRC from a different package called `lexicon` instead of getting it from `tidytext`:

``` r
## lexicon - An alternative to load the NRC lexicon ----
if (!is.element("lexicon", installed.packages()[, 1])) {
  install.packages("lexicon", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}
require("lexicon")

### NRC ----
# Instead of:
# nrc <- get_sentiments("nrc")
# View(nrc)

# Try this:
data(hash_nrc_emotions)
nrc <- hash_nrc_emotions
nrc <- nrc %>%
  mutate(word = token, sentiment = emotion) %>%
  select(word, sentiment)
View(nrc)
```

Unfortunately, the NRC from the `lexicon` package has 8,265 observations whereas the one from the `tidytext` package has 13,872 observations. But this is a simpler alternative. A more complicated alternative is to download it directly from the source here: [https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm](https://saifmohammad.com/WebPages/NRC-Emotion-Lexicon.htm).

Let me know if the alternative code above works before attempting to download directly from the source.

**Comment by Paula-Wang** [comment]
The alternative code has worked. Thank you for the assistance.

**Comment by Paula-Wang** [comment]
It is now throwing a new error:
Error: 'C:/Users/PAULIN~1/AppData/Local/textdata/textdata/Cache/nrc/NRC-Emotion-Lexicon/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt' does not exist.

**Comment by course-files** [comment]
Could this be because you ran the old code again by mistake? The new code should replace the old code so that you can proceed to STEP 5. after executing this:

``` r
## lexicon - An alternative to load the NRC lexicon ----
if (!is.element("lexicon", installed.packages()[, 1])) {
  install.packages("lexicon", dependencies = TRUE,
                   repos = "https://cloud.r-project.org")
}
require("lexicon")

### NRC ----
# Instead of:
# nrc <- get_sentiments("nrc")
# View(nrc)

# Try this:
data(hash_nrc_emotions)
nrc <- hash_nrc_emotions
nrc <- nrc %>%
  mutate(word = token, sentiment = emotion) %>%
  select(word, sentiment)
View(nrc)
```

If it is still giving an error, then you can commit and push your changes to GitHub so that I comment on the exact lines to replace.

**Comment by Paula-Wang** [comment]
I replaced the old code with the new one then it ran NRC but it refused to run step 5 and gave this error:
Error: 'C:/Users/PAULIN~1/AppData/Local/textdata/textdata/Cache/nrc/NRC-Emotion-Lexicon/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt' does not exist.

**Comment by course-files** [comment]
Okay, replace all occurrences of this from STEP 5 onwards:
`get_sentiments("nrc")`

with this:
`nrc`

For example, instead of the following:
``` r
# STEP 5. Inner Join the Likes/Wishes with the Corresponding Sentiment(s) ----
evaluation_likes_filtered_nrc <- evaluation_likes_filtered %>%
  inner_join(get_sentiments("nrc"),
             by = join_by(`Likes (tokenized)` == word),
             relationship = "many-to-many")

evaluation_wishes_filtered_nrc <- evaluation_wishes_filtered %>%
  inner_join(get_sentiments("nrc"),
             by = join_by(`Wishes (tokenized)` == word),
             relationship = "many-to-many")
```

STEP 5 will be:

``` r
# STEP 5. Inner Join the Likes/Wishes with the Corresponding Sentiment(s) ----
evaluation_likes_filtered_nrc <- evaluation_likes_filtered %>%
  inner_join(nrc,
             by = join_by(`Likes (tokenized)` == word),
             relationship = "many-to-many")

evaluation_wishes_filtered_nrc <- evaluation_wishes_filtered %>%
  inner_join(nrc,
             by = join_by(`Wishes (tokenized)` == word),
             relationship = "many-to-many")
```

This is because the get_sentiments function is still searching for NRC in the `tidytext` package.

**Comment by Paula-Wang** [comment]
It has now run successfully to the end. Thank you for the help.

**Comment by course-files** [comment]
I'm glad it has worked. Thank you also for the detailed error messages.

In this case, then I will not record the marks for the quiz we did so that it is fair for everyone. There are probably others who were also unable to load NRC from `tidytext`. They can refer to this issue for an alternative.

**Comment by Paula-Wang** [comment]
I have sent the issue to them
